USE [master]
GO

/****** Object:  Database [GamingTable]    Script Date: 30/09/2015 18:05:14 ******/
CREATE DATABASE [GamingTable]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GamingTable', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\GamingTable.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'GamingTable_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\GamingTable_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [GamingTable] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GamingTable].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [GamingTable] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GamingTable] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GamingTable] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GamingTable] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GamingTable] SET ARITHABORT OFF 
GO

ALTER DATABASE [GamingTable] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [GamingTable] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GamingTable] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GamingTable] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GamingTable] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GamingTable] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GamingTable] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GamingTable] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GamingTable] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GamingTable] SET  DISABLE_BROKER 
GO

ALTER DATABASE [GamingTable] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GamingTable] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GamingTable] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GamingTable] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GamingTable] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GamingTable] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [GamingTable] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GamingTable] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [GamingTable] SET  MULTI_USER 
GO

ALTER DATABASE [GamingTable] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GamingTable] SET DB_CHAINING OFF 
GO

ALTER DATABASE [GamingTable] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [GamingTable] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [GamingTable] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [GamingTable] SET  READ_WRITE 
GO

